name: dev-env
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/paszln/bookinfo-ratings:dev
  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: get-credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: k8s
          location: asia-southeast1-a
          credentials: ${{ secrets.ITKMITL_GKE_CREDENTIALS }}
      - name: deploy
        uses: deliverybot/helm@v1
        with:
          helm: helm3
          release: bookinfo-dev-ratings
          namespace: student31-bookinfo-dev
          chart: k8s/helm
          value-files: k8s/helm-values/values-bookinfo-dev-ratings.yaml
          values: |
            {
              "extraEnv": {
                "COMMIT_SHA": "${{ github.sha }}"
              }
            }
  test:
    need: deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Run acceptance test
        run: curl http://itkmitl.bookinfo.dev.opsta.net/student31/ratings/health | grep "Ratings is working"