name: hello-world
on: [push]
jobs:
  print-hello-world:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: echo "Hello World"
      - run: ls -l